# Generated by Django 4.0.1 on 2022-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profilepic')),
                ('ism', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('yosh', models.IntegerField()),
                ('kasb', models.CharField(max_length=200)),
            ],
        ),
    ]
